### ISSUE TITLE
Use rlite for tests

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#109]
https://github.com/seppo0010/rlite

might also be an option to use this on heroku without (paid) addons

**Comment by Jake0oo0** [comment]
This is actually really cool, but I think it might be better to test with redis, only because there might be a small bug in this software, that produces different results in production. Same reason that I would use postgres in development if I plan on using postgres in production, to make sure there are no minor bugs that are caused by the difference in databases.
