### ISSUE TITLE
Should not 404 for valid players missing custom skin

### ISSUE THREAD

**Issue by confuser** [crafatar/crafatar#111]
Raised here to start a discussion which started at https://github.com/BanManagement/BanManager-WebUI/issues/39 as to whether or not 404 is a correct response when retrieving a player's skin, whom does not have a custom one, i.e. is Alex or Steve.

**Comment by jomo** [comment]
I agree we should return a `200.` The argumentation is that users **do** have a skin, it's just the default instead of a custom one.

Returning `404` seems to result in not rendering images in Blink (i.e. Google Chrome).
We'll need to discuss what to do with `503`s and Blink. Haven't tested it, but I assume that they also won't render.

related: #87

**Comment by jomo** [comment]
Please note that capes will continue to return `404` as `text/plain` because users do not have a default / fallback cape.

We'll continue discussion about `503` in #87.
