### ISSUE TITLE
Fix http/https for examples on website

### ISSUE THREAD

**Issue by Jake0oo0** [crafatar/crafatar#130]
I finally found a fix for this in another project, just need a reminder to get it done.

**Comment by jomo** [comment]
JavaScript, I guess?

**Comment by Jake0oo0** [comment]
no

**Comment by jomo** [comment]
I think this has been fixed since 60387c8c7c028a412deab9c06f0b46d3b5ae8a21, really. It just defaults to https.
Since the node app itself uses http, there's no (good, reliable) way to tell if someone initially accessed a downstream reverse-proxy via https on the back-end. The only thing you can do is check the document protocol via JS.

If someone forks/uses this but doesn't use https, they can still ~~change it~~ use https on their site.
