### ISSUE TITLE
Head Render request

### ISSUE THREAD

**Issue by voodootje0** [crafatar/crafatar#210]
Dear Crafatar,

I would like to request something for the head renders, could the resolution be equivalent, now it is 120x111. Also the size modifier is broken for head renders could you made it so it works.

Kind regards,
voodootje0

**Comment by jomo** [comment]
While there have been some changes to renders in the past that would have affected size and ratio, we tried to minimize the differences to not break websites or other applications that use Crafatar. Unfortunately this would be a breaking change. I don't see an overwhelmingly good reason to give head renders a 1:1 ratio anyway.

Regarding the `size` modifier, as [documented on our website](https://crafatar.com/#meta-parameters), it's only used for avatars and specifies the image width/height in pixels, whereas renders use `scale`, which affects the size, but does not represent the width or height in pixels. That is because otherwise, the render image would need to be scaled resulting in uneven sizes of rendered skin pixels, which looks very weird and unproportional, especially for small images.
