### ISSUE TITLE
New Mojang API rate limit (Alex/Steve skins)

### ISSUE THREAD

**Issue by Electroid** [crafatar/crafatar#260]
https://crafatar.com

**Comment by jomo** [comment]
The problem is that Mojang started locking down their servers this morning. As a result, their AWS CloudFront rejects any requests once you're past a certain limit.

To Crafatar, all requests to Mojang's servers look like this:

![image](https://user-images.githubusercontent.com/3585743/77196585-ef1d0b80-6ae3-11ea-8e7a-46008b7db085.png)

---

Unfortunately we can't do much about it other than spinning up more servers (read: more IP addresses) and then load balancing between them. This would actually increase load on Mojang's servers because less of those requests will be cached, but it would generate less traffic per IP address.

Unfortunately I don't know what exactly the limit is before requests start to get blocked.

Crafatar is free to use, in fact it costs money to run it, so I can't simply buy a 100 servers and be done with it.

---

## Proper solution for everyone affected by this

If you need working avatars _now_, I suggest you run your own instance of Crafatar. It barely needs any resources and runs efficiently on very small servers. This repo has all the code in it. The [crafatar/setup](https://github.com/crafatar/setup) repo is slightly out of date, but documents roughly how our current server is set up.

## Short term solution for crafatar.com

I'll try to spin up a few cheap cloud servers and load balance between them, but again I don't know how many are necessary and I don't want to pay for them long term. 

## Long term solution for crafatar.com

I'll try to reach someone at Mojang to discuss this, perhaps they could add an exception for our servers as it's in their interest to reduce server load. I'm not confident this will work, but at least I'll try.

If that doesn't work, we'll need more servers. The more servers there are to load balance between, the better this will work. So _please_ run your own instance of Crafatar! With your consent, we could add the server to a pool of load balanced Crafatar servers which share the load.

---

To make this easier, I will update this repo (it hasn't been changed in a while because it just worked™️). I'll also improve and simplify documentation and required steps to run a Crafatar instance, including a docker image.

**Comment by jomo** [comment]
crafatar.com is running on 6 servers for now.

But apparently the rate limit is _extremely low_, about 10 req/s. crafatar.com easily receives over 600 req/s. That's why it's currently still very slow. It would require more than 60 servers to handle those requests without errors. The average is lower, about 120 per second (on a weekend), but that would still require 12 servers.

IP addresses cost € 1.19/month on Hetzner, that's cheaper, but still not something I'm willing to pay long term.

**Comment by jomo** [comment]
In other news, I just added a docker image and simple instructions to run Crafatar. See the project README!

**Comment by jomo** [comment]
Status update: crafatar.com is now running with 10 different IP addresses. 9 of them will process 10 req/s and the last one will process any remaining requests, which means that this IP address is probably banned by Mojang most or all of the time and uncached avatars will fall back to steve/alex skins when processed by this IP. Currently, these are still a lot, but the majority of requests are now handled properly.

## Important

I want to stress that this is a temporary workaround and not a sustainable solution.  
**Please [run your own Crafatar](https://github.com/crafatar/crafatar/#installation) instance**!

**Comment by jomo** [comment]
Update: I was able to reach someone at Mojang and they reverted the rate limit.

crafatar.com should be fully operational again.

Thanks Mojang! \\o/

**Comment by jomo** [comment]
Reopening this.

The rate limit now appears to be 6000 per minute (100/s). When that limit is exceeded, _all_ requests are denied for the next 5 minutes.

crafatar.com regularly needs to process more than 6000 requests per minute and many of these require external requests against the Mojang API. So during popular hours (like now), we're constantly blocked.

---

I have contacted Mojang about this on Thursday, but they didn't answer yet.

**Comment by jomo** [comment]
Meanwhile I'm thinking about methods to work around this issue:

- Rate limit incoming requests per IP
  - ❌ nope, breaks websites with many images, such as leaderboards etc
- Rate limiting total incoming requests
  - ❌ nope, randomly breaks things, including infrequent single requests
- Increase cache expiry time
  - Browser (1 hour) to 4 days
    - This is also (mostly?) used by Cloudflare
  - Crafatar cache (20 minutes) to 12 hours
- Rate limit outgoing requests to 100/s
  - Cancel any further outgoing requests, continue as if the request was blocked
  - For cached skins, skip checking for changes, but reset age to current time (so it's not dropped when removing old files from cache)
  - This will return default skins for uncached skins, but not completely reject the request

**Comment by jomo** [comment]
> The rate limit now appears to be 6000 per minute (100/s). When that limit is exceeded, all requests are denied for the next 5 minutes.

Apparently the rate limit is much lower once exceeded. Once you're blocked, CloudFront won't unblock you when you're constantly sending < 100/s. You'll need to stop or drastically lower the amount of requests.

The changes from my last comment went into effect on crafatar.com with [version 2.1.2](https://github.com/crafatar/crafatar/releases/tag/v2.1.2).

So far it's looking good. That is, requests are still failing when we receive a lot of them, but we're no longer hitting the rate limit and most of all requests are answered properly \o/

**Comment by bloggy** [comment]
Hi there,
all of the head images have the ALEX skin now, tried with many different UUIDs. What's the problem? Can you fix it?

**Comment by jomo** [comment]
Apparently there's two issues now \o/

- A little over a week ago, Mojang _again_ applied their rate limit of 10 requests per second (after having reverting it from 10 to 100). This rate limiting is done by CloudFront and returns a `403 Forbidden` for a while when you exceed the rate limit.
  - A workaround for this has been implemented in 15a4f17560eb22697177343f5112910aece927db, Crafatar now throttles outgoing requests (i.e. makes them fail), so the server is not blocked by CloudFront
- Apparently Mojang's session server (behind CloudFront) is now also returning `429 Too Many Requests` for pretty much all requests.
  - They used to do this when requesting the same UUID more than once per minute, but you could send as many unique requests as you like
  - They changed that, and now they're allowing **10 requests per minute**, total

Mojang's [API status](https://status.mojang.com/check) reports that the session server status is `red` (meaning major problems), so let's _hope_ this is just a temporary measure.

Unfortunately I can't really do anything about it, these issues are 100% caused by Mojang 😕

**Comment by jomo** [comment]
**Update**: I'm again in contact with Mojang, the situation should have improved a lot now!

---

Specifically, we're no longer hitting the _new_ session server rate limit of 10 requests per _minute_, but we're still hitting the old CloudFront limit of ~10 requests per _second_.

Thus, some requests will still fail when crafatar.com receives a lot of requests that aren't cached by neither crafatar nor the user.

I'm also discussing this remaining issue with Mojang, but I don't expect to hear back before Monday.

**Comment by Aberdeener** [comment]
@jomo Hey, if it helps you guys out I am more than willing to start paying for more IP's for you. If you're interested, let me know and we can chat more.

**Comment by jomo** [comment]
Thanks @Aberdeener! I'm still hoping to be able to sort it out with Mojang. So far it looks like they want to work with us to solve the problem, but getting a reply just takes a couple of days every time.

Besides, the 10 req/s limit makes using more IP addresses pretty much unfeasible, unless you have 600 IPv4 addresses to spare.

**Comment by Aberdeener** [comment]
Sounds good! Let me know if things change. Have a great day/night and thank you for Crafatar!

**Comment by james090500** [comment]
Just wondering if you managed to get anywhere with Mojang, we're still getting a lot of alex/steve skins for players on our site unfortunately.

**Comment by james090500** [comment]
It may be worth investigating this here:

https://github.com/Electroid/mojang-api

It bakes multiple API requests into a single request and also uses cloudflare workers to avoid Mojang lovely API limit

https://api.ashcon.app/mojang/v2/user/james090500

**Comment by fjeddy** [comment]
This issue is killing Crafatar, I've been trying to fetch avatars for 4 days straight now, without success. From time to time I might get one through, but that's it.

I also cache the avatars for 7 days, and all it's trying to do is update the cache / check for changes.

**Comment by MisterFixx** [comment]
FYI, i solved this issue for [MCHeads](https://mc-heads.net) with https://github.com/MisterFixx/MojangPipe

**Comment by Electroid** [comment]
As @james090500 mentioned, I run a Mojang proxy API on Cloudflare Workers, which by nature, distributes requests over a *lot* of Cloudflare IPs.

I'm going to make a PR to add a configuration option to change the session server url (which would allow users to point it to a proxy like mine). Stay tuned!

**Comment by jomo** [comment]
@fjeddy that specific problem was probably not entirely caused by this issue. I just noticed that crafatar had crashed, failed to restart and also somehow didn't show up in the monitoring. That was about 5 days ago. It caused requests to be answered from a helplessly overloaded fallback server, which is why you couldn't fetch avatars. Sorry about that, I've taken some measures to prevent this in the future and it should be better now. Your requests might of course still hit the rate limit, but eventually they should get through.

**Comment by jomo** [comment]
Btw thanks all for chiming in and offering your help!

Using proxies is something I considered, but would ultimately prefer not to do. For one, it's technically "nonsense" and not really in the interest of either API users nor Mojang. It adds more possible points of failure and more delay to requests.

After all, Mojang seems to be willing to whitelist crafatar.com's requests. I believe so far it's just a communication problem. They won't be whitelisting proxies, so proxies are going to hit the rate limit very quick. If more than just one application is using those proxies, the risk of them hitting the limit becomes unpredictable.

- Using a bunch of free proxies is going to be extremely unreliable.
- Paying for (more reliable) proxies is going to be expensive at the current scale of crafatar.com.

Even if Cloudflare is "big enough" in terms of IP addresses that this won't be an issue, it costs 0.50$ per 1M requests. crafatar.com receives tens to hundreds millions of (uncached) requests – most notably not in a predictable way – so this could easily cost $100 or more per month. @Electroid if you have cheap (or free) access to CF workers, I would consider using your API **if** that's a viable option *and* Mojang won't whitelist crafatar.com. I don't want to cause anyone additional costs and although I really appreciate the offers of everyone in here, I'd also prefer if Crafatar's operation doesn't entirely depend on someone having cheap access to resources and/or being generous.

---

To be transparent about the communication with Mojang so far: I've sent a few mails back and forth with what seems to be the right person (their infrastructure tech lead). They have whitelisted crafatar's IP from their app level rate limit (`429 Too Many Requests`), but not from their CloudFront rate limit (`403 Forbidden`). I told them this was still an issue. They once again asked for the IP address to whitelist, to which I replied that it hasn't changed and that we're having an issue with CloudFront.

That was 2 weeks ago. Unfortunately I haven't heard back since. I'm not sure if this is a technical issue they can't easily solve, if they don't understand what our issue is, or if they just have too many other things to do and keep forgetting about it. I also don't want to annoy them with an email every other day, but I've once again asked if anything can be done about it.

**Comment by jomo** [comment]
@Electroid regardless of using proxies or not, I do think that having the sessions URL and the textures URL configurable is a good idea 👍

It's essentially these two lines here: https://github.com/crafatar/crafatar/blob/0d2fe02cbc62195d0b67c3361351e4bfbbbae094/lib/networking.js#L8-L9

And perhaps an entry in `config.js` should do.

But if you don't want to go through the hassle of forking etc, I can also just include this the next time I touch the code (soon-ish).

**Comment by Aberdeener** [comment]
Thank you for your dedication and transparency! Hope this works out for
everyone

**Comment by jomo** [comment]
After clarification of the issue, Mojang has now whitelisted crafatar.com at their CloudFront rate limit, too! \o/

# 🎈🎉 🥳 

---

**crafatar.com should now be able to answer all requests properly**. Unfortunately this relies on whitelisting, so self-hosted Crafatar instances won't benefit from that, but I can't really do anything about it. Self-hosted instances will have to stay below the rate limit, use proxies, or contact Mojang for whitelisting as well.

**Comment by fjeddy** [comment]
Glad this has gotten resolved @jomo, but if Mojang is so "willing" to whitelist applications, why do they have a rate limit to begin with? Is this a question you've might have gotten an answer to through your correspondence with them?

**Comment by MisterFixx** [comment]
Hey @jomo, mind leaving an E-Mail for me to talk to them too? I would love to avoid the rate limit for MCHeads, thanks.

**Comment by jomo** [comment]
FYI, I have reverted the caching changes to crafatar.com mentioned above in https://github.com/crafatar/crafatar/issues/260#issuecomment-605524272 back to the default.

Skins are now, again

- re-checked by Crafatar after 20 minutes
- cached in web browsers for 60 minutes

**Comment by ljcool2006** [comment]
[I still get an Alex skin.](https://crafatar.com/avatars/01e4d3733d91446990670010a11f838b?size=64&overlay)

**Comment by MisterFixx** [comment]
> [I still get an Alex skin.](https://crafatar.com/avatars/01e4d3733d91446990670010a11f838b?size=64&overlay)

Not still, again.
Mojang is currently returning a lot of 403 and 429 responses to client, perhaps due to some sort of outage
The status of the session server on https://mc-heads.net/mcstatus keeps flicking on and off
