### ISSUE TITLE
MIssing overlays on some players

### ISSUE THREAD

**Issue by nstringham** [crafatar/crafatar#280]
## description of problem
some players such as [20d6334b7f9541ebbf7f860205ebf846](https://crafatar.com/avatars/20d6334b7f9541ebbf7f860205ebf846?overlay), [f5667ad6b4b3434ba58f2ed2396f62f2](https://crafatar.com/avatars/f5667ad6b4b3434ba58f2ed2396f62f2?overlay), and [b44d2d5272dc49c28185b2d6a158d80a](https://crafatar.com/avatars/b44d2d5272dc49c28185b2d6a158d80a?overlay) don't show an overlay when the overlay parameter is present.

##  steps to reproduce:
1. set a skin with a hat by going to https://namemc.com/skin/8fb5faa25f6931de and clicking apply (any method of setting any skin with a hat will likely work but this is how I did it)
2. load Minecraft and join a multiplayer server (this step might not be required)
3. go to `https://crafatar.com/avatars/<your UUID>?overlay`
### expected behavior:
![download](https://user-images.githubusercontent.com/44071655/111570935-37fdb380-877c-11eb-830a-c1950165c4a3.png)
### actual behavior:
![b44d2d5272dc49c28185b2d6a158d80a](https://user-images.githubusercontent.com/44071655/111571032-709d8d00-877c-11eb-9156-f6bc9954aee0.png)
### skin used for example: 
![8fb5faa25f6931de](https://user-images.githubusercontent.com/44071655/111571085-8a3ed480-877c-11eb-8aa4-25d0a9667319.png)

### a note on reproducibility:
it appears this bug is somewhat unpredictable and I cannot guarantee that this method will reproduce the bug. I would do further testing but crafatar.com uses a cache making testing slow.

## other notes:
I have considered the possibility that this bug may be related to the `Hat` option in Minecraft's Skin Customization options however I am fairly certain this has no affect on this bug.

**Comment by nstringham** [comment]
Something I forgot to mention in my original comment is that this is a regression. I don't know exactly when it stopped working as expected but it seems to be within the last week or so.

**Comment by jomo** [comment]
Thank you for reporting this!

Crafatar stores plain-avatars and overlay-avatars as two separate PNG files. When a skin has no overlay, only the plain-avatar is stored. When someone then requests an overlay-avatar, crafatar checks if there's an overlay-avatar and otherwise just serves the plain-avatar.

I recently deleted plain-avatars and overlay-avatars due to disk space issues. These users must have been stored again between deleting their plain-avatars and their overlay-avatars, so the overlay-avatars went missing. I'll make sure to keep this in mind when deleting files again.

The issue should now be fixed. Note that Cloudflare might keep the cached version around for a short while.

**Comment by nstringham** [comment]
Thank you. It seems to be working as expected now
