### ISSUE TITLE
Google Ads Crafatar Malicious Software Detected

### ISSUE THREAD

**Issue by L0thric-HM** [crafatar/crafatar#300]
I've had a bunch of problems using Crafatar services on my website because Google Ads stopped all my campaigns after a verification detected something malicious there. I contacted the Google support and they, one more time, told me to remove the links from Crafatar.

The question is: What from Crafatar is makin Google remove Ads?

**Comment by MisterFixx** [comment]
Google seem to have changed policies about who can get ads on their website these days, while giving out as vague of a reason to why your ads were rejected as possible, it is unfortunately making it very hard to provide a free service for everybody while staying afloat from just Adsense revenue and donations

**Comment by jomo** [comment]
Crafatar doesn't interact with Google. You need to ask Google about Google's actions.

---

Off topic: If you need money to run your website, consider asking for donations, making it a paid website, finding a sponsor, or just pay the hosting yourself rather than contributing to an ecosystem that annoys users, makes ad blockers necessary and has no respect for privacy.
