### ISSUE TITLE
Fix ImageCleaner on Heroku

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#4]
*(edited)*

* [x] change file date (async) when time changes in redis
* [x] detect free disk space
* [x] remove oldest files
* [x] run worker every so often

**Comment by mrapple** [comment]
Just a suggestion, don't store images at all. Only cache UUIDs/texture URLs in redis. CloudFlare will take care of the rest.

**Comment by jomo** [comment]
That's a nice idea, but we also want people to be able to self-host this (i.e. without CloudFlare)

**Comment by jomo** [comment]
This happens on heroku only

**Comment by Jake0oo0** [comment]
Doesn't mean we necessarily shouldn't fix it. We currently provide the files to run Crafatar w/ Heroku, so we should either drop support for it, or make sure it works correctly.

**Comment by jomo** [comment]
Hmm yea that's true. Would have to patch `node-df` or find an alternative though.

------

@mrapple I thought about your suggestion again and while it would work for the most cases, it wouldn't work for some cases, e.g. errors on Mojang's side in which case we would fall back to a potentially outdated image on our side.

**Comment by mrapple** [comment]
Sorry, not sure I follow. How will not caching the image file result in an outdated image?

**Comment by Tama63** [comment]
@jomo I had another go at interpreting the comments on this issue, I think what @mrapple is trying to say is:

1. When an image is requested it is automatically cached on Cloudflare's edge servers
2. This means that you don't need to keep a local copy because one already exists on their servers
3. When the cache is invalidated Cloudflare will simply request a new image from the crafatar server.

Although not everyone uses cloudflare this could be a configuration setting as a vast majority of people in the community do.

**Comment by jomo** [comment]
Yep, has been discussed in #75 already :)
