### ISSUE TITLE
Benchmarks vs other services

### ISSUE THREAD

**Issue by Jake0oo0** [crafatar/crafatar#50]

**Comment by jomo** [comment]
https://gist.github.com/jomo/57a1654c8ef10bfda1e8

Raw data, didn't do anything fancy with them yet.
Aside from that we seem to be the fastest :)

**Comment by connor4312** [comment]
You should benchmark the applications themselves -- not the apps running on servers -- if you want things to be meaningful! (at least for open source projects) Different applications are under different loads at any given time, and are hosted on and behind different services. Try to examine applications in isolation when possible.

Also, yes, a digest would be nice :)

**Comment by Jake0oo0** [comment]
While true, we want to provide information regarding which service would be best to use, based on several factors, including first-requests, caching, and location. The general user is going to be using the service that we provide, and not hosting their own instance of Crafatar.

**Comment by jomo** [comment]
What connor said is a valid point, it would be nice to include it.
However I'm going to close this. I don't have the time to set up all the other servers - many of them aren't even open source. I'm not too interested in the results because I know crafatar is quite fast anyway.
If someone feels like benchmarking their own instances or wants to use the raw data for some fancy graphs, let me know.
