### ISSUE TITLE
Option to not download images at all

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#75]
Original idea by @mrapple in #4 to let e.g. CloudFlare manage all the caching and not care about it on our side. We would only forward images to the client through CloudFlare which would then take care of the caching for us.

**Comment by mrapple** [comment]
:+1:

**Comment by jomo** [comment]
I forgot to reply to this from #4:

> @mrapple I thought about your suggestion again and while it would work for the most cases, it wouldn't work for some cases, e.g. errors on Mojang's side in which case we would fall back to a potentially outdated image on our side.

-
> Sorry, not sure I follow. How will not caching the image file result in an outdated image?

I wasn't really clear, sorry for that.

This is an (IMO important) feature of crafatar. If we can't get an updated image (i.e. check for skin changes + download new skin) from Mojang, we might [still have the old hash](https://github.com/crafatar/crafatar/blob/8fc63a99034636d8f640dc916ac8b32a2bd10304/modules/helpers.js#L199-L200) in redis (and the image stored locally) and [use that](https://github.com/crafatar/crafatar/blob/8fc63a99034636d8f640dc916ac8b32a2bd10304/modules/helpers.js#L232-L234).

As skin changes happen rarely, chances are that our version is actually the current skin.

If we don't store the image, we could only request it from Mojang which is likely to fail if it failed a moment ago. In that case we can't deliver the image to CloudFlare and we would have to send a `502` with Steve.

A possible workaround is to implement image-hash-based URLs and redirect all requests to those URLs.
The effect would be that CloudFlare caches those image for us in the same way we would cache them locally, but I fear this would require a lot more changes and I'm unsure if it's really worth it.

**Comment by mrapple** [comment]
Very well said. I didn't post this here, but we just rewrote our avatar server. We also now store skin blobs indefinitely for users. It's up to you, but I would seriously considering removing all file storage and just keep the blob stored somewhere. For us, this guards against most Mojang services going down. However, if there is a textutes.minecraft.net outage and CloudFlare does not have the cache, we will serve a steve skin. 

Fun stuff, obviously you might just want to close this issue and I understand your rationale for doing so. Since we aren't planning on using crafatar anymore it really doesn't matter to me :D

**Comment by jomo** [comment]
Well, using an external cache or caching images on our own basically results in the same thing, with the difference that we know how to translate userids to images without the need of redirecting.
An external cache would most likely have a performance advantage, but redirecting `/userid -> /image-hash` probably also slows things down.

----

I'm closing this because you're the only one who asked for it, but the idea isn't bad.
We will be happy to accept pull requests if anyone feels the need :octocat:

**Comment by mrapple** [comment]
:+1:
