### ISSUE TITLE
Fall back to cached skins, renders, and capes if possible

### ISSUE THREAD

**Issue by Bastikeks** [crafatar/crafatar#98]
i tested my username and it shows steve as my avatar : 
https://crafatar.com/skins/Bastikeks
this is my actual skin: http://mcskinsearch.com/skin/Bastikeks
Is it just some kind of caching problem or how do i get this working? Tested this also with some other users and there it works...

**Comment by Jake0oo0** [comment]
Looks like it works now. @jomo are we caching skins and profiles even if there was a server error when attempting to get them?

**Comment by jomo** [comment]
I *think* we only cache avatars, wanted to open an issue for that after looking into it

**Comment by jomo** [comment]
Actually we cache everything of course, but IIRC we only **use** the cached version of avatars when we have trouble with Mojang

**Comment by jomo** [comment]
To explain @Bastikeks what most likely happened:
We tried to check for updates on your skin, but couldn't receive it (either hit Mojang's rate limit, their servers failed to reply properly or there were some network issues).
What happens in this case with avatars is that we just fall back to an older version of the avatar (if available) but this feature is not yet implemented.

However, this is only a temporary issue that happens rarely and it starts working again after we successfully checked for another update.

**Comment by Jake0oo0** [comment]
@jomo aren't we caching skin and cape hashes even if we get a 500/non-404?

**Comment by jomo** [comment]
Quite sure we cache at all times (including null hashes) but not on errors. Will look into it after work

**Comment by Jake0oo0** [comment]
we should only cache if it's a 404, and let it continue to request again if necessary if it's a 500 or server error.

**Comment by jomo** [comment]
Well you forgot 200 :laughing:

For 429 (rate limit) we could *update the timestamp* if we already have a hash (if not, we will have to cache null). I think right now we overwrite it with null when that happens. Updating the timestamp would cause it to return the cached image. We could also set the timestamp to some time in the past so that the skin can be requested again 1 minute later (when the rate limit is lifted).

**Comment by Jake0oo0** [comment]
We can use redis TTL!!! 👌

**Comment by jomo** [comment]
hmm, but we don't want to delete the cape because the skin couldn't be received. using the timestamp should work

**Comment by jomo** [comment]
Alright, so I had a look at the code and the fallback for cached hashes is done [inside `helpers.get_image_hash`](https://github.com/crafatar/crafatar/blob/6cb4a46ac7c028eced2e43c24329f98bec8e5010/modules/helpers.js#L211-L214) which is called by `get_avatar`, `get_cape` and `get_skin`, which is also called by `get_render`.

So, in fact, this should be the case for all of the images we server.
My guess is that CloudFlare cached the skin image when it had some sort of issues, but it cached the avatar when it was just fine.

I'm afraid we can't look into details because it was a temporary issue that went away too fast. Unfortunately we're [still on heroku](#95) and our free Papertrail plan has hit the 1.5 GB limit and log processing has been paused.
![doh!](http://i4.ifrm.com/5959/69/emo/homer_doh.gif)

**Comment by jomo** [comment]
@Bastikeks this should no longer happen due to #99 / #101 :sunglasses:
